import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { connection } from "next/server";
import { Suspense } from "react";
import { CartProvider } from "@/context/CartContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Syukur Kedai",
    absolute: "Angkringan",
  },
  description: "Generated by create next app",
};

async function UTSSR() {
  await connection();
  return <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <ClerkProvider afterSignOutUrl="/">
        <CartProvider>
          <html lang="en">
            <body className={`${dmSans.className}`}>
              <UTSSR />
              {children}
              <Toaster />
            </body>
          </html>
        </CartProvider>
      </ClerkProvider>
    </Suspense>
  );
}
